services:
  api1:
    build: .
    environment:
      - PORT=3001      
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "225M"

  api2:
    build: .
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "225M"
